### ISSUE TITLE
Update library to Node Module

### ISSUE THREAD

**Issue by LucasAlfare** [IceCreamYou/MainLoop.js#31]
Since last commit was 2 years ago is a nice idea update the library to fully work with the node module system (a.k.a. `export default`/`import`), once this feature is more mature now.

**Comment by IceCreamYou** [comment]
Reasonable request I suppose. If I was going to do this I'd want to have the compile step output in both UMD and ES6 Module format.

**Comment by FlorentMasson** [comment]
I'm also interested by this as it doesn't seem to be currently working when imported as an ES6 module

```
mainloop.js:152 Uncaught TypeError: Cannot set properties of undefined (setting 'MainLoop')
    at mainloop.js:152:6
    at mainloop.js:753:27
```
